<a href="https://colab.research.google.com/github/ashwinij-7/Machine-Learning/blob/main/Logistic_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pandas numpy matplotlib

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

Import dataset from Kaggle

In [4]:
# Install dependencies as needed:
!pip install kagglehub[pandas-datasets]
import kagglehub
import os

# Download dataset
path = kagglehub.dataset_download("abhaypanchal/ipl-dataset-for-model-train")

print("Dataset downloaded to:", path)

# Show files inside dataset folder
print(os.listdir(path))

Requirement already satisfied: kagglehub[pandas-datasets] in /usr/local/lib/python3.12/dist-packages (1.0.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.14 in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (0.1.18)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (26.0)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (4.67.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (2.2.2)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kagglesdk<1.0,>=0.1.14->kagglehub[pandas-datasets]) (5.29.6)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas->kagglehub[pandas-datasets]) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->kagglehub[pandas-datasets]) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->kagglehub[pandas-datasets]) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->kagglehub[pandas-datasets]) (2026.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub[pandas-datasets]) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub[pandas-datasets]) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub[pandas-datasets]) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub[pandas-datasets]) (2026.2.25)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->kagglehub[pandas-datasets]) (1.17.0)
Downloading to /root/.cache/kagglehub/datasets/abhaypanchal/ipl-dataset-for-model-train/1.archive...

100%|██████████| 5.27k/5.27k [00:00<00:00, 7.40MB/s]

Extracting files...
Dataset downloaded to: /root/.cache/kagglehub/datasets/abhaypanchal/ipl-dataset-for-model-train/versions/1
['ipl_match_win.csv']

In [6]:
import pandas as pd
import os

# Full file path
csv_path = os.path.join(path, "ipl_match_win.csv")

# Load dataset
df = pd.read_csv(csv_path)

# Preview data
print(df.head())
print(df.shape)

   runs_first_6_overs  wickets_lost_pp current_run_rate  boundary_count  \
0                31.0              3.0              NaN             2.0
1                68.0              4.0             9.58             9.0
2                80.0              4.0             5.74             2.0
3                75.0              3.0            11.62             2.0
4                48.0              3.0             9.92            11.0

   home_venue  top3_batsmen_in  extras_conceded  match_won
0         0.0              1.0              3.0          0
1         1.0              0.0             19.0          0
2         1.0              1.0             19.0          0
3         1.0              1.0              5.0          1
4         1.0              1.0              0.0          1
(593, 8)

Feature Engineering

In [8]:
df.head()

,runs_first_6_overs,wickets_lost_pp,current_run_rate,boundary_count,home_venue,top3_batsmen_in,extras_conceded,match_won
0,31.0,3.0,NaN,2.0,0.0,1.0,3.0,0
1,68.0,4.0,9.58,9.0,1.0,0.0,19.0,0
2,80.0,4.0,5.74,2.0,1.0,1.0,19.0,0
3,75.0,3.0,11.62,2.0,1.0,1.0,5.0,1
4,48.0,3.0,9.92,11.0,1.0,1.0,0.0,1

In [10]:
print(df.dtypes)

runs_first_6_overs    float64
wickets_lost_pp       float64
current_run_rate       object
boundary_count        float64
home_venue            float64
top3_batsmen_in       float64
extras_conceded       float64
match_won               int64
dtype: object

In [11]:
df['current_run_rate'] = pd.to_numeric(df['current_run_rate'], errors='coerce')

In [12]:
print(df.dtypes)

runs_first_6_overs    float64
wickets_lost_pp       float64
current_run_rate      float64
boundary_count        float64
home_venue            float64
top3_batsmen_in       float64
extras_conceded       float64
match_won               int64
dtype: object

In [15]:
df.corr(numeric_only=True)['match_won']

runs_first_6_overs    0.250610
wickets_lost_pp      -0.364106
current_run_rate      0.272888
boundary_count        0.293271
home_venue            0.116041
top3_batsmen_in       0.185527
extras_conceded      -0.048308
match_won             1.000000
Name: match_won, dtype: float64

In [31]:
print(X.isnull().sum())

wickets_lost_pp        0
boundary_count        17
current_run_rate      23
runs_first_6_overs     0
top3_batsmen_in        0
dtype: int64

Import Model

In [26]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [27]:
X = df[
    [
        'wickets_lost_pp',
        'boundary_count',
        'current_run_rate',
        'runs_first_6_overs',
        'top3_batsmen_in'
    ]
]

y = df['match_won']

In [32]:
X = X.fillna(X.mean())

In [33]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [34]:
model = LogisticRegression()

In [35]:
model.fit(X_train, y_train)

LogisticRegression()

Evaluation

In [36]:
acc = accuracy_score(y_test, model.predict(X_test)) * 100
print(f"Logistic Regression model accuracy: {acc:.2f}%")

Logistic Regression model accuracy: 86.55%

In [37]:
from sklearn.metrics import precision_score, recall_score

In [38]:
y_pred = model.predict(X_test)

precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)

print("Precision:", precision)
print("Recall:", recall)

Precision: 0.9080459770114943
Recall: 0.9080459770114943

In [39]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.75      0.75      0.75        32
           1       0.91      0.91      0.91        87

    accuracy                           0.87       119
   macro avg       0.83      0.83      0.83       119
weighted avg       0.87      0.87      0.87       119